### ISSUE TITLE
Terrain position

### ISSUE THREAD

**Issue by ArchDemons** [tonihele/OpenKeeper#248]
Currently we have map with start coordinates (-1, -1).  I think, this is not good.  If we decide move it, I do that.

Secondary question. Need decide how we get Tile coordinates. Currently - class Point, because it easy to use as array index. But all our world use Vectors (Vector2f and Vector3f). Should we stay use Point (when we say tile coordinate, we think Point, when we say Point we think tile coordinate ^_^) or change it to Vector2f e.g. ?

**Comment by ufdada** [comment]
Good point. If we rework this, we shouldn't forget about work positions (like digging).
As far as i could figure out, dk uses at least 9 points on a tile were something can happen. (example: gold thrown away by imps when the treasure is full, or digging, especially on gems)

**Comment by tonihele** [comment]
I don't see a problem using Point & Vector2f together, Vector2f signifies that we mean 3D world and Point a tile. Vector3f we don't need I think (except they come from the scene natively, but we never use the "height").

For gold dropping I'm in progress of giving Vector2f and IInteractableObject to dropping. So that we would have "infinite" amount of drop points on tile. But also merge for gold. For jobs also with multiple workers this point thing is partially implemented.

**Comment by tonihele** [comment]
Not a very good answer :) But yes, I like Point, but it is also AWT (an android problem?). Easy to substitute with our own, but somewhat easy to use Vector2f as well.

At WorldState:
    public Point getTileCoordinates(Vector3f location)

**Comment by ArchDemons** [comment]
To many casts from float to int. Maybe really own class with blackjack and ... It`s not very difficult
