### ISSUE TITLE
How to change Language?

### ISSUE THREAD

**Issue by Kulturnilpferd** [tonihele/OpenKeeper#350]
I have used german data to change OpenKeeper to german but this didn't work... Any suggestions?

**Comment by tonihele** [comment]
There is no way to change the language. OpenKeeper is completely reliant on the original game assets. Texts and fonts all come from there. So if you had German DK 2, you should have German OpenKeeper.

We have only couple of text items fixed in English (some new 3D terms) and the splash screens are available for every supported language on the original game, so that is based on your OS locale which one we pick.

You need to be little bit more specific now that how it did not work. What language you have or you have no language at all? Is there an error message? Screen shot goes a long way too...
