### ISSUE TITLE
OpenKeeper installation Done sucessfull, but got some bugs ingame

### ISSUE THREAD

**Issue by ecore276** [tonihele/OpenKeeper#351]
Hey guys,

today i tried 3-4 hours for getting fnished the installation of open keeper.

1 hours ago i finished and was very exicted about the game. 
There are some bugs at my game.

1. Cant begin new campaign ( there are all games free to play ) 
2. Ingame i cant hear some sounds like "claps" my creatures
3. If i used the "ESC-Button" the game is closed and im back in window
4. I cant use "save" and "Load"
5. The game is jerking 

I owned the orginal version from GOG.
I installed the game and open keeper 3 times and alltimes the same result.

did i do some mistakes ?

best regards sebastian

**Comment by tonihele** [comment]
Thank you for the intrest in our project. It is just that we are on pre
alpha state and shit ton of features wait to be implemented 😊

We are still trying to figure out the sound structure properly and having
all levels playable just provides us the convenience we need at this stage
of development. The ESC key is also since we spent most of our time in the
IDE rather than in-game.

We do have milestone 0.1 release layed out.
