### ISSUE TITLE
.STD file hints

### ISSUE THREAD

**Issue by d1nuc0m** [tonihele/OpenKeeper#406]
I read on the wiki that the support for .STD files is almost complete, maybe to complete it you could have a look to the information gathered by Game Extractor ([here](https://www.watto.org/specs.html?specs=Archive_SDT)) [[GPLv2, on SourceForge](https://sourceforge.net/projects/gameextractor/)] and Dragon Unpacker (HyperRipper may help in general with other filetypes) [[MPLv2, here](https://www.elberethzone.net/en/dragon-unpacker.html)]

**Comment by tonihele** [comment]
Thanks. We do however seem to be quite far here. At least if one compares to the sources you gave. We extract all the sound files and can play them. Dragon Unpacker was I think one of the source materials as well in the beginning.

There are few unknown values, that is why I guess we deemed only 95% worthiness.

Anyways, I don't think there is anything to do with this ticket. Feel free to comment if you think otherwise. Thank you for your time!

**Comment by d1nuc0m** [comment]
Thank you, probably the most interesting part might be HyperRipper, as it has a "brute force" approach, it might be useful for other file types not fully reversed engineered yet
