### ISSUE TITLE
Add credits to main menu

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#55]
Add credits to main menu. The real original credits that is. I didn't find them anywhere on the resources. Maybe we just need to copy + paste them from the Internet. And check that all is there. We should still use the translations though (titles), they are in the main dictionary.

Nice & simple task

**Comment by ufdada** [comment]
I took the credits directly from dk2 via screenshots and writing down them manually (since the credits from the internet are way different). I replaced the titles with the corresponding translations and I already got the infinite scrolling working :). There are still some issues left but I will make a pr asap, so you can have a look at it.

**Comment by tonihele** [comment]
Oh nice!
